### ISSUE TITLE
crashes when interacting with a forge

### ISSUE THREAD

**Issue by hospisss** [LordDeatHunter/Alloy-Forgery#114]
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.21.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at net.minecraft.class_437.method_25394(class_437.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:104) ~[client-intermediary.jar:?]
	at io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:156) ~[owo-lib-0.9.3+1.19.jar:?]
	at wraith.alloyforgery.client.AlloyForgeScreen.method_25394(AlloyForgeScreen.java:39) ~[wraith-alloy-forgery-2.0.20+1.19.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 7 more

**Comment by Noaaan** [comment]
Please see https://github.com/wisp-forest/alloy-forgery/issues/80 first

**Comment by hospisss** [comment]
i already installed charmfixer, It did not help

**Comment by Noaaan** [comment]
Please see https://fabricmc.net/wiki/player:tutorials:logs_ml:windows. We need logs to help you debug what mods could be causing the crash.

**Comment by Noaaan** [comment]
Bumping this issue. Are you still experiencing this problem? We are unable to help you without anything to go off.

**Comment by Noaaan** [comment]
Closing this as it has not received a response in a long time. Should you still be experiencing this issue, please re-open it or make a new issue.
