### ISSUE TITLE
Alloy forgery crashing for some reason

### ISSUE THREAD

**Issue by SithTrooper9** [LordDeatHunter/Alloy-Forgery#126]
Whenever I open Minecraft, Alloy forgery crashes because of something. Anyone got any idea what it is?

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'alloy_forgery'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.BootstrapMethodError: java.lang.RuntimeException: Mixin transformation of wraith.alloyforgery.block.ForgeControllerBlockEntity failed
	at wraith.alloyforgery.block.ForgeControllerBlockEntity$Type.<init>(ForgeControllerBlockEntity.java:455)
	at wraith.alloyforgery.block.ForgeControllerBlockEntity$Type.<clinit>(ForgeControllerBlockEntity.java:452)
	at wraith.alloyforgery.AlloyForgery.<clinit>(AlloyForgery.java:35)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50)
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117)
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 7 more
Caused by: java.lang.RuntimeException: Mixin transformation of wraith.alloyforgery.block.ForgeControllerBlockEntity failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:427)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 16 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422)
	... 20 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [megane-alloy-forgery.mixins.json:AccessorForgeControllerBlockEntity from mod megane-alloy-forgery] from phase [DEFAULT] in config [megane-alloy-forgery.mixins.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 23 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching fuel:I in wraith/alloyforgery/block/ForgeControllerBlockEntity for megane-alloy-forgery.mixins.json:AccessorForgeControllerBlockEntity from mod megane-alloy-forgery->@Accessor[FIELD_GETTER]::getFuel()I [INJECT Applicator Phase -> megane-alloy-forgery.mixins.json:AccessorForgeControllerBlockEntity from mod megane-alloy-forgery -> Apply Accessors ->  -> Locate -> megane-alloy-forgery.mixins.json:AccessorForgeControllerBlockEntity from mod megane-alloy-forgery->@Accessor[FIELD_GETTER]::getFuel()I]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:519)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:502)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:476)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1411)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1071)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 23 more

**Comment by BasiqueEvangelist** [comment]
What version of Megane are you using?

**Comment by SithTrooper9** [comment]
7.9.0

**Comment by BasiqueEvangelist** [comment]
Could you try using a newer version of Megane? (7.10.0 or 7.9.1)

**Comment by SithTrooper9** [comment]
ok ill try it

**Comment by Dragon-Seeker** [comment]
Any update to such still being a problem?

**Comment by Noaaan** [comment]
We have not heard from you in a while. I think it is safe to assume you resolved this issue. Feel free to let us know if this isn't the case
