### ISSUE TITLE
Crash when opening singleplayer (Mod conflict?)

### ISSUE THREAD

**Issue by ZannCoelz** [LordDeatHunter/Alloy-Forgery#139]
I was trying out this mod and when I tried opening the singleplayer world creation screen the game crashed. I have several other mods installed and when I tried replicating the crash with only alloy forgery the game didn't crash. So probably a mod conflict?

Here's the crash report:
[crash-2024-07-04_18.27.55-client.txt](https://github.com/user-attachments/files/16100885/crash-2024-07-04_18.27.55-client.txt)

**Comment by mantevian** [comment]
I got a similar problem with Mythic Metals which uses Alloy Forgery, and I was able to find out that disabling Remove Reloading Screen fixed the crash

**Comment by T9es** [comment]
Can confirm. The crash is there. There's also a lot of sewage spilling out in the console when the mod is added on a server. I have no clue if this can be connected in any way, but users that crashed for some random reason also couldn't join back. No idea if this mod causes that, there's no way to tell. The logs don't say anything specific.

**Comment by Ollie434** [comment]
Also having issue with players intermittently crashing when trying to connect to the server, and crashing of the instance when leaving the server. Can also confirm that disabling the Remove Reloading Screen mod fixed the crashes both on server join and single player world creation, however crash still persists on server disconnect.

**Comment by Noaaan** [comment]
This issue should hopefully be fixed (as of https://github.com/wisp-forest/alloy-forgery/commit/ef4c4c77948020743ebb65f3345d06578473a29c).
Plan is to release this as a beta later today for testing

**Comment by the-arkhive** [comment]
Also having a similar issue, I assume with Mythic Metals as well. I don't have "Remove Reloading Screen" installed, so that fix won't do it for me.

```
---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2024-07-15 04:57:00
Description: Initializing game

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'medievalweapons'!
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
	at net.minecraft.client.main.Main.main(Main.java:239)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.NoClassDefFoundError: net/dragonloot/item/DragonToolMaterial
	at net.medievalweapons.compat.CompatItems.loadItems(CompatItems.java:365)
	at net.medievalweapons.init.ItemInit.init(ItemInit.java:300)
	at net.medievalweapons.MedievalMain.onInitialize(MedievalMain.java:22)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399)
	... 6 more
Caused by: java.lang.ClassNotFoundException: net.dragonloot.item.DragonToolMaterial
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 10 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:477)
```

**Comment by Noaaan** [comment]
> Also having a similar issue, I assume with Mythic Metals as well. I don't have "Remove Reloading Screen" installed, so that fix won't do it for me.

This issue seems to be completely unrelated to Alloy Forgery. Please report it to DragonLoot instead

**Comment by Noaaan** [comment]
The latest version should fix these potential issues. I suggest trying out 2.2.2, and reporting any new issues if they arise
