### ISSUE TITLE
Resource Bundle error

### ISSUE THREAD

**Issue by zc1108aaa** [LordDeatHunter/Alloy-Forgery#157]
[latest.log](https://github.com/user-attachments/files/18228555/latest.log)

**Comment by Noaaan** [comment]
There are simply way too many mods to manually reproduce this issue. I doubt it happens solely because of Alloy Forgery, and rather some specific mod is causing this. 
```
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7972()" because "this.output" is null
	at wraith.alloyforgery.recipe.AlloyForgeRecipe.method_8110(AlloyForgeRecipe.java:203) ~[【前置-合金熔炉】wraith-alloy-forgery-2.0.16+1.18.2.jar:?]
	at net.minecraft.class_1863.redirect$iab000$libjf-data-manipulation-v0$onPutRecipe(class_1863.java:10543) ~[client-intermediary.jar:?]
```
LibJF seems to be using redirects here, which might be incompatible. I would start there. If you are able to reproduce the issue, please provide steps on how to do so
