### ISSUE TITLE
Charm incompat - Crashing when opening a forge

### ISSUE THREAD

**Issue by lithospace** [LordDeatHunter/Alloy-Forgery#80]
When opening a forge controller, the game crashes.
Here is the bottom of the latest.log
REI
[14:19:53] [VoiceChatAuthenticationThread/INFO]: Trying to authenticate voice connection
[14:19:53] [VoiceChatConnectionThread/INFO]: Server acknowledged authentication
[14:19:53] [NativeInitializationThread/INFO]: Using Opus version 'libopus 1.3.1'
[14:19:54] [Render thread/WARN]: Received passengers for unknown entity
[14:20:43] [Render thread/ERROR]: ########## GL ERROR ##########
[14:20:43] [Render thread/ERROR]: @ Render
[14:20:43] [Render thread/ERROR]: 65540: Invalid scancode -1
[14:20:54] [Render thread/WARN]: @Final field field_25883:Lnet/minecraft/class_4970$class_4973; in charm.mixins.json:more_portal_frames.AddValidPortalFrameBlocksMixin from mod charm should be final
[14:20:55] [Render thread/WARN]: Configuration conflict: there is more than one oshi.architecture.properties file on the classpath
[14:20:56] [Render thread/INFO]: Clearing audio channels
[14:20:56] [Render thread/INFO]: Stopping microphone thread
[14:20:56] [Render thread/INFO]: Disconnecting voicechat
[14:20:56] [Render thread/INFO]: Minimap session finalized.
[14:20:56] [Render thread/INFO]: Finalizing world map session...
[14:20:56] [Thread-20/INFO]: World map force-cleaned!
[14:20:56] [Render thread/INFO]: World map session finalized.
[14:20:56] [Render thread/INFO]: Unloading server config for easymagic
[14:20:56] [Render thread/INFO]: Unloading server config for enchantinginfuser
[14:20:56] [Render thread/INFO]: Unloading server config for pickupnotifier
[14:20:57] [Render thread/INFO]: Stopping worker threads
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266803)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266820)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266805)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2626.redirect$fbj001$polymer_replaceState(class_2626.java:533)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266801)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Netty Client IO #1/ERROR]: Invalid BlockState ID (266801)! Couldn't match it with any existing value!
[14:20:57] [Netty Client IO #1/ERROR]: Caused by: net.minecraft.class_2637.redirect$fbl000$polymer_decodeState(class_2637.java:532)
[14:20:57] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:890) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:768) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.method_44604(Main.java:244) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:51) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.10.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.10.jar:?]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:1013) ~[?:?]
	at java.util.ArrayList$Itr.next(ArrayList.java:967) ~[?:?]
	at net.minecraft.class_437.method_25394(class_437.java:106) ~[client-intermediary.jar:?]
	at net.minecraft.class_465.method_25394(class_465.java:104) ~[client-intermediary.jar:?]
	at io.wispforest.owo.ui.base.BaseOwoHandledScreen.method_25394(BaseOwoHandledScreen.java:156) ~[owo-lib-0.8.5+1.19.jar:?]
	at wraith.alloyforgery.client.AlloyForgeScreen.method_25394(AlloyForgeScreen.java:39) ~[wraith-alloy-forgery-2.0.17+1.19.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:881) ~[client-intermediary.jar:?]
	... 7 more
Mods:
roughlyenoughitems 9.1.568
alloy_forgery 2.0.17+1.19
owo 0.8.5+1.19
fabric-api 0.66.0+1.19.2

**Comment by lithospace** [comment]
https://pastebin.com/vxZ534Gk
Latest
https://pastebin.com/jDbmfwaj
Crash Report

**Comment by Noaaan** [comment]
After investigating this a bit further via the Wraith Coding Sesh Discord, this is a crash caused with latest Alloy Forgery (2.0.17) and Charm. 
Reverting to 2.0.16 seems to mitigate this issue, although we are still looking into why this happens.

**Comment by Dragon-Seeker** [comment]
Issue report in [Charm](https://github.com/svenhjol/Charm/issues/878) Github.

**Comment by Dragon-Seeker** [comment]
Working Solution is to download this Custom Mod that will fix the issue by disabling any modules that are using the offensive API.
Modrinth: [Link](https://modrinth.com/mod/charm-fixer)
Curseforge: [Link](https://www.curseforge.com/minecraft/mc-mods/charm-fixer)

**Comment by Dragon-Seeker** [comment]
Closing this issue should no longer be present on new versions of charm.
