### ISSUE TITLE
REI Plugin Issue

### ISSUE THREAD

**Issue by gamerpotion** [LordDeatHunter/Alloy-Forgery#85]
Hi, I have been informed that the Alloy forgery plugin may not be set up correctly for REI.  Currently installed on my modpack - https://www.curseforge.com/minecraft/modpacks/darkrpg

Have seen this in the REI logs:

```[18:51:21] [main/ERROR] [REI] AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery] plugin failed to reloadable-plugin/DisplaySerializerRegistryImpl/!
java.lang.RuntimeException: Cannot load class me.shedaniel.rei.api.client.registry.display.DisplayCategory in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at wraith.alloyforgery.compat.rei.AlloyForgeryCommonPlugin.registerDisplaySerializer(AlloyForgeryCommonPlugin.java:18)
	at me.shedaniel.rei.impl.common.display.DisplaySerializerRegistryImpl.acceptPlugin(DisplaySerializerRegistryImpl.java:75)
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:340)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:198)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:330)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:196)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:328)
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123)
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:114)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$onInitialize$3(RoughlyEnoughItemsCore.java:144)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_156.method_43498(class_156.java:958)
	at net.minecraft.class_156.method_43499(class_156.java:946)
	at net.minecraft.server.Main.main(Main.java:156)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
[18:51:21] [main/ERROR] [REI] AlloyForgeryCommonPlugin of AlloyForgeryCommonPlugin [alloy_forgery] plugin failed to reloadable-plugin/MenuInfoRegistryImpl/!
java.lang.RuntimeException: Cannot load class me.shedaniel.rei.api.client.registry.display.DisplayCategory in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:454)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:407)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:186)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:347)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at wraith.alloyforgery.compat.rei.AlloyForgeryCommonPlugin.registerMenuInfo(AlloyForgeryCommonPlugin.java:13)
	at me.shedaniel.rei.impl.common.transfer.MenuInfoRegistryImpl.acceptPlugin(MenuInfoRegistryImpl.java:149)
	at me.shedaniel.rei.impl.common.transfer.MenuInfoRegistryImpl.acceptPlugin(MenuInfoRegistryImpl.java:48)
	at me.shedaniel.rei.api.common.registry.Reloadable.acceptPlugin(Reloadable.java:72)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$9(PluginManagerImpl.java:340)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$pluginSection$4(PluginManagerImpl.java:198)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.lambda$startReload$10(PluginManagerImpl.java:330)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.pluginSection(PluginManagerImpl.java:196)
	at me.shedaniel.rei.impl.common.plugins.PluginManagerImpl.startReload(PluginManagerImpl.java:328)
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:123)
	at me.shedaniel.rei.RoughlyEnoughItemsCore._reloadPlugins(RoughlyEnoughItemsCore.java:114)
	at me.shedaniel.rei.RoughlyEnoughItemsCore.lambda$onInitialize$3(RoughlyEnoughItemsCore.java:144)
	at java.base/java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:787)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_4014.method_18365(class_4014.java:69)
	at net.minecraft.class_156.method_43498(class_156.java:958)
	at net.minecraft.class_156.method_43499(class_156.java:946)
	at net.minecraft.server.Main.main(Main.java:156)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69)
````

**Comment by Dragon-Seeker** [comment]
[Fixed](https://github.com/wisp-forest/alloy-forgery/commit/594c4c8736d7fab4806a4528aab370e78db0dd92)

**Comment by gamerpotion** [comment]
> [Fixed](https://github.com/wisp-forest/alloy-forgery/commit/594c4c8736d7fab4806a4528aab370e78db0dd92)

Hey thanks :) just wanted to check if this was included in an update?
